<?php return [
	'optional' => 'No Skill',
	'opt' => 'No Skill',
	'empty' => 'No Skill',
	'save yourselves' => '"Save yourselves!" (Kurzick)',
	'aura of holy might' => 'Aura of Holy Might (Kurzick)',
	'elemental lord' => 'Elemental Lord (Kurzick)',
	'ether nightmare' => 'Ether Nightmare (Kurzick)',
	'selfless spirit' => 'Selfless Spirit (Kurzick)',
	'shadow sanctuary' => 'Shadow Sanctuary (Kurzick)',
	'signet of corruption' => 'Signet of Corruption (Kurzick)',
	'spear of fury' => 'Spear of Fury (Kurzick)',
	'summon spirits' => 'Summon Spirits (Kurzick)',
	'triple shot' => 'Triple Shot (Kurzick)',
	'help' => '"Help Me!"',
];
